framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
              enabled: "%kernel.debug%"
            marking_store:
              type: 'method'
              property: 'state'
            supports:
              - App\Entity\Comment
            initial_marking: submitted
            places:
              - ham
              - potential_spam
              - published
              - rejected
              - spam
              - submitted
            transitions:
              accept:
                from: submitted
                to: ham
              might_be_spam:
                from: submitted
                to: potential_spam
              reject_spam:
                from: submitted
                to: spam
              publish:
                from: potential_spam
                to: published
              reject:
                from: potential_spam
                to: rejected
              publish_ham:
                from: ham
                to: published
              reject_ham:
                from: ham
                to: rejected
