<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ConferenceController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function index(Request $request): Response
    {
//        autogenerated code

//        return $this->render('conference/index.html.twig', [
//            'controller_name' => 'ConferenceController',
//        ]);

        $greetings = '';
        if ($name = $request->query->get('hello')) {
            $greetings = sprintf('<h1>Hello, %s!</h1>', htmlspecialchars($name));
        }

        return new Response(<<<TMP
<html lang="en">
    <body>
        $greetings
        <img src="/images/under-construction.gif" alt="under_construction">
    </body>
</html>
TMP
        );
    }
}
